name: pr-and-release-build.yml
on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Sidecar Build"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Checkout sidecar project
        uses: actions/checkout@v6

      - name: Build cross-platform binaries
        run: make build

      - name: Run tests
        run: make tests

      - name: Build cross-platform packages
        run: make packages